version: "3"
services:
  rubixcore:
    build: .
    ports:
      - "2018:2018"
    env_file: 
      - .env-rubixcore
    depends_on:
      - database
      - rabbitmq
    volumes:
      - .:/go/src/github.com/hackstock/rubixcore
  database:
    image: mysql:5.6.41
    command: mysqld --sql_mode=""
    ports:
      - "3306:3306"
    env_file: 
      - .env-mysql
  rabbitmq:
    image: rabbitmq:3-management
    ports: 
      - "15672:15672"
    env_file: 
      - .env-rabbitmq